# Generated by Django 3.0.7 on 2020-06-26 09:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.FloatField(default=0)),
                ('genre', models.CharField(max_length=32)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.CharField(max_length=512)),
                ('artist_name', models.CharField(max_length=128)),
                ('artist_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SongModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('artist_name', models.CharField(max_length=128)),
                ('artist_id', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlbumsBackend.AlbumModel')),
            ],
        ),
        migrations.AddField(
            model_name='albummodel',
            name='songs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlbumsBackend.SongModel'),
        ),
        migrations.AddConstraint(
            model_name='albummodel',
            constraint=models.CheckConstraint(check=models.Q(price__lt=0), name='price_lt_0'),
        ),
    ]
