# Generated by Django 3.0.7 on 2020-06-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlbumsBackend', '0002_auto_20200627_1019'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='albummodel',
            name='price_lt_0',
        ),
        migrations.AddConstraint(
            model_name='albummodel',
            constraint=models.CheckConstraint(check=models.Q(price__gte=0), name='price_gte_0'),
        ),
    ]
