# Generated by Django 3.0.7 on 2020-06-28 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Category name')),
                ('description', models.TextField(blank=True, verbose_name='Category description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Категория продукта',
                'verbose_name_plural': 'Категории продуктов',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Product name')),
                ('image', models.ImageField(blank=True, upload_to='products_images')),
                ('short_desc', models.CharField(blank=True, max_length=60, verbose_name='Product short description')),
                ('description', models.TextField(blank=True, verbose_name='Product description')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Product price')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Product quantity in stock')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchapp.ProductCategory')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
